// ReactivityProfiler.idl : IDL source for ReactivityProfiler
//

// This file will be processed by the MIDL tool to
// produce the type library (ReactivityProfiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "corprof.idl";

[
	uuid(beb5385e-61a6-43aa-ad6e-02fd424fd82f),
	version(1.0),
]
library ReactivityProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(09c5b5d7-62d2-4448-911d-2e1346a21110)
	]
	coclass RxProfiler
	{
		[default] interface ICorProfilerCallback;
		interface ICorProfilerCallback2;
		interface ICorProfilerCallback3;
		interface ICorProfilerCallback4;
		interface ICorProfilerCallback5;
		interface ICorProfilerCallback6;
		interface ICorProfilerCallback7;
		interface ICorProfilerCallback8;
		interface ICorProfilerCallback9;
	};
};
